[build]
builder = "NIXPACKS"
buildCommand = "npm ci --cache /tmp/npm-cache && npm run build"

[deploy]
startCommand = "node build"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
